server:
  port: 9000
spring:
  application:
    name: testh2webconsole				#项目名称尽量用小写
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource: # 指定数据源
    platform: h2		#指定数据源类型
    schema: classpath:schema.sql		#指定h2数据库的建表脚本
    data: classpath:data.sql
  h2:
    console:
      enabled: true		#指定h2数据库的insert脚本

spring.datasource.url: jdbc:h2:mem:test #配置h2数据库的连接地址
spring.datasource.driver-class-name: org.h2.Driver #配置JDBC Driver
spring.datasource.username: root #配置数据库用户名
spring.datasource.password: 123456
