--- 
before_script: 
  - "cd testprovider"
  - "cd .."
branches: 
  only: 
    - master
env: 
  - DB=mysql

before_install:
  - wget http://apache.claz.org/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
  - tar zxvf apache-maven-3.3.9-bin.tar.gz
  - chmod +x apache-maven-3.3.9/bin/mvn
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$PWD/apache-maven-3.3.9/bin:${PATH}
  - hash -r

cache:
  directories:
    - $HOME/.m2

install:
  - "echo henghenghahi "
  - "mvn install -Dmaven.test.skip=true"
jdk: 
  - oraclejdk8
Maven version:
  - 3.3.9
language: java
mysql: 
  database: es
  encoding: utf8
  password: ~
  username: root
notifications: 
  email: 
    - 993590008@qq.com
script: 
  - "cd testprovider"
  - "cd .."
  - "echo 'heihei' "
