--- 
before_script: 
  - "cd testprovider"
  - "cd .."
branches: 
  only: 
    - master
env: 
  - DB=mysql
install: 
  - "mvn install -Dmaven.test.skip=true"
jdk: 
  - oraclejdk8
language: java
mysql: 
  database: es
  encoding: utf8
  password: ~
  username: root
notifications: 
  email: 
    - 993590008@qq.com
script: 
  - "cd testprovider"
  - "mvn testprovider"
  - "cd .."
  - "cd test"
  - "mvn testcustomer -Pit"
