server:
  port: 8020
spring:
  application:
    name: microservice-consumer-user				#项目名称尽量用小写


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/	#指定注册中心的地址
  instance:
    preferIpAddress: true

ribbon:
  eureka:
    enabled: true

logging:
  level: debug